In [1]:
import pandas as pd

In [2]:
df_tables = pd.read_html('https://fbref.com/en/players/2964fd20/Gustavo-Scarpa')

In [3]:
df_tables

[  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                 Date                Day               Comp              Round
 0         2023-11-12                Sun       Super League     Regular season
 1         2023-11-05                Sun       Super League     Regular season
 2         2023-10-30                Mon       Super League     Regular season
 3         2023-09-24                Sun       Super League     Regular season
 4         2023-09-17                Sun       Super League     Regular season

   Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
                Venue             Result              Squad           Opponent
 0               Away              W 2–0         Olympiacos    Asteras Tripoli
 1               Home              L 2–4         Olympiacos               PAOK
 2               Away              W 2–0         Olympiacos          OFI Crete
 3               Home              W 4–0         Olympiacos         AO Kifisia
 4               Away              D 1–1         Olympiacos         AEK Athens

   Unnamed: 8_level_0 Unnamed: 9_level_0  ... SCA Passes               Carries  \
                Start                Pos  ... GCA    Cmp Att Cmp% PrgP Carries
 0                  Y                 AM  ... NaN    NaN NaN  NaN  NaN     NaN
 1                  N                NaN  ... NaN    NaN NaN  NaN  NaN     NaN
 2                  N                NaN  ... NaN    NaN NaN  NaN  NaN     NaN
 3                  Y                 CM  ... NaN    NaN NaN  NaN  NaN     NaN
 4                  N                NaN  ... NaN    NaN NaN  NaN  NaN     NaN

        Take-Ons      Unnamed: 36_level_0
   PrgC      Att Succ        Match Report
 0  NaN      NaN  NaN        Match Report
 1  NaN      NaN  NaN        Match Report
 2  NaN      NaN  NaN        Match Report
 3  NaN      NaN  NaN        Match Report
 4  NaN      NaN  NaN        Match Report

 [5 rows x 37 columns],
             Unnamed: 0_level_0          Unnamed: 1_level_0  \
                         Season                         Age
 0                         2014                          20
 1                         2015                          21
 2                         2016                          22
 3                         2017                          23
 4                         2018                          24
 5                         2019                          25
 6                         2020                          26
 7                         2021                          27
 8                         2022                          28
 9                    2022-2023                          28
 10                   2023-2024                          29
 11                  10 Seasons                  10 Seasons
 12                         NaN                         NaN
 13       Palmeiras (5 Seasons)       Palmeiras (5 Seasons)
 14      Fluminense (4 Seasons)      Fluminense (4 Seasons)
 15       Olympiacos (1 Season)       Olympiacos (1 Season)
 16  Nott'ham Forest (1 Season)  Nott'ham Forest (1 Season)
 17                         NaN                         NaN
 18         Série A (9 Seasons)         Série A (9 Seasons)
 19     Super League (1 Season)     Super League (1 Season)
 20   Premier League (1 Season)   Premier League (1 Season)

             Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                          Squad            Country               Comp
 0                   Fluminense             br BRA         1. Série A
 1                   Fluminense             br BRA         1. Série A
 2                   Fluminense             br BRA         1. Série A
 3                   Fluminense             br BRA         1. Série A
 4                    Palmeiras             br BRA         1. Série A
 5                    Palmeiras             br BRA         1. Série A
 6                    Palmeiras             br BRA         1. Série A
 7                    Palmeiras             br BRA         1. Série A
 8                    Palmeiras             br BRA         1. Série A
 9              Nott'ham Forest            eng ENG  1. Premier League
 10                  Olympiacos             gr GRE    1. Super League
 11                     4 Clubs                NaN          3 Leagues
 12                         NaN            Country               Comp
 13       Palmeiras (5 Seasons)                NaN           1 League
 14      Fluminense (4 Seasons)                NaN           1 League
 15       Olympiacos (1 Season)                NaN           1 League
 16  Nott'ham Forest (1 Season)                NaN           1 League
 17                         NaN                NaN                NaN
 18         Série A (9 Seasons)                NaN                NaN
 19     Super League (1 Season)                NaN                NaN
 20   Premier League (1 Season)                NaN                NaN

    Unnamed: 5_level_0 Unnamed: 6_level_0 Playing Time                ...  \
                LgRank                 MP       Starts    Min    90s  ...
 0                 6th                  6            0     36    0.4  ...
 1                13th                 28           24   2181   24.2  ...
 2                13th                 34           34   2994   33.3  ...
 3                14th                 38           37   3159   35.1  ...
 4                 1st                 12            8    653    7.3  ...
 5                 3rd                 27           19   1564   17.4  ...
 6                 7th                 26           10   1168   13.0  ...
 7                 3rd                 31           21   1836   20.4  ...
 8                 1st                 35           31   2575   28.6  ...
 9                16th                  6            2    181    2.0  ...
 10                3rd                  7            3    343    3.8  ...
 11                NaN                250          189  16690  185.4  ...
 12             LgRank                 MP       Starts    Min    90s  ...
 13                NaN                131           89   7796   86.6  ...
 14                NaN                106           95   8370   93.0  ...
 15                NaN                  7            3    343    3.8  ...
 16                NaN                  6            2    181    2.0  ...
 17                NaN                NaN          NaN    NaN    NaN  ...
 18                NaN                237          184  16166  179.6  ...
 19                NaN                  7            3    343    3.8  ...
 20                NaN                  6            2    181    2.0  ...

    Per 90 Minutes                                                          \
               Ast   G+A  G-PK  G+A-PK    xG   xAG  xG+xAG  npxG  npxG+xAG
 0            0.00  0.00  0.00    0.00   NaN   NaN     NaN   NaN       NaN
 1            0.12  0.33  0.21    0.33   NaN   NaN     NaN   NaN       NaN
 2            0.30  0.54  0.24    0.54   NaN   NaN     NaN   NaN       NaN
 3            0.34  0.40  0.06    0.40   NaN   NaN     NaN   NaN       NaN
 4            0.14  0.41  0.14    0.28   NaN   NaN     NaN   NaN       NaN
 5            0.23  0.46  0.12    0.35  0.31  0.21    0.52  0.18      0.38
 6            0.39  0.46  0.08    0.46  0.16  0.37    0.53  0.16      0.53
 7            0.64  0.83  0.15    0.78  0.28  0.39    0.67  0.24      0.63
 8            0.45  0.70  0.10    0.56  0.36  0.42    0.77  0.22      0.64
 9            0.00  0.00  0.00    0.00  0.13  0.02    0.14  0.13      0.14
 10           0.00  0.00  0.00    0.00   NaN   NaN     NaN   NaN       NaN
 11           0.33  0.51  0.13    0.46  0.29  0.35    0.64  0.20      0.55
 12            Ast   G+A  G-PK  G+A-PK    xG   xAG  xG+xAG  npxG  npxG+xAG
 13           0.42  0.62  0.12    0.53  0.30  0.36    0.65  0.21      0.56
 14           0.27  0.43  0.16    0.43   NaN   NaN     NaN   NaN       NaN
 15           0.00  0.00  0.00    0.00   NaN   NaN     NaN   NaN       NaN
 16           0.00  0.00  0.00    0.00  0.13  0.02    0.14  0.13      0.14
 17            NaN   NaN   NaN     NaN   NaN   NaN     NaN   NaN       NaN
 18           0.34  0.52  0.14    0.48  0.30  0.36    0.65  0.21      0.56
 19           0.00  0.00  0.00    0.00   NaN   NaN     NaN   NaN       NaN
 20           0.00  0.00  0.00    0.00  0.13  0.02    0.14  0.13      0.14

    Unnamed: 35_level_0
                Matches
 0              Matches
 1              Matches
 2              Matches
 3              Matches
 4              Matches
 5              Matches
 6              Matches
 7              Matches
 8              Matches
 9              Matches
 10             Matches
 11                 NaN
 12             Matches
 13                 NaN
 14                 NaN
 15                 NaN
 16                 NaN
 17                 NaN
 18                 NaN
 19                 NaN
 20                 NaN

 [21 rows x 36 columns],
             Unnamed: 0_level_0          Unnamed: 1_level_0  \
                         Season                         Age
 0                         2014                          20
 1                         2015                          21
 2                         2016                          22
 3                         2017                          23
 4                         2018                          24
 5                         2019                          25
 6                         2020                          26
 7                         2021                          27
 8                         2022                          28
 9                    2022-2023                          28
 10                   2023-2024                          29
 11                  10 Seasons                  10 Seasons
 12                         NaN                         NaN
 13       Palmeiras (5 Seasons)       Palmeiras (5 Seasons)
 14      Fluminense (4 Seasons)      Fluminense (4 Seasons)
 15       Olympiacos (1 Season)       Olympiacos (1 Season)
 16  Nott'ham Forest (1 Season)  Nott'ham Forest (1 Season)
 17                         NaN                         NaN
 18         Série A (9 Seasons)         Série A (9 Seasons)
 19     Super League (1 Season)     Super League (1 Season)
 20   Premier League (1 Season)   Premier League (1 Season)

             Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                          Squad            Country               Comp
 0                   Fluminense             br BRA         1. Série A
 1                   Fluminense             br BRA         1. Série A
 2                   Fluminense             br BRA         1. Série A
 3                   Fluminense             br BRA         1. Série A
 4                    Palmeiras             br BRA         1. Série A
 5                    Palmeiras             br BRA         1. Série A
 6                    Palmeiras             br BRA         1. Série A
 7                    Palmeiras             br BRA         1. Série A
 8                    Palmeiras             br BRA         1. Série A
 9              Nott'ham Forest            eng ENG  1. Premier League
 10                  Olympiacos             gr GRE    1. Super League
 11                     4 Clubs                NaN          3 Leagues
 12                         NaN            Country               Comp
 13       Palmeiras (5 Seasons)                NaN           1 League
 14      Fluminense (4 Seasons)                NaN           1 League
 15       Olympiacos (1 Season)                NaN           1 League
 16  Nott'ham Forest (1 Season)                NaN           1 League
 17                         NaN                NaN                NaN
 18         Série A (9 Seasons)                NaN                NaN
 19     Super League (1 Season)                NaN                NaN
 20   Premier League (1 Season)                NaN                NaN

    Unnamed: 5_level_0 Unnamed: 6_level_0 Standard            ...             \
                LgRank                90s      Gls   Sh  SoT  ...  Dist   FK
 0                 6th                0.4        0  NaN  NaN  ...   NaN  NaN
 1                13th               24.2        5  NaN  NaN  ...   NaN  NaN
 2                13th               33.3        8  122   31  ...   NaN  NaN
 3                14th               35.1        2  115   29  ...   NaN  NaN
 4                 1st                7.3        2   25    7  ...   NaN  NaN
 5                 3rd               17.4        4   55   23  ...  26.0    7
 6                 7th               13.0        1   45   15  ...  26.6    7
 7                 3rd               20.4        4   73   21  ...  25.5   16
 8                 1st               28.6        7  112   33  ...  25.4   26
 9                16th                2.0        0    7    1  ...  26.9    0
 10                3rd                3.8        0  NaN  NaN  ...   NaN  NaN
 11                NaN              185.4       33  554  160  ...  25.8   56
 12             LgRank                90s      Gls   Sh  SoT  ...  Dist   FK
 13                NaN               86.6       18  310   99  ...  25.7   56
 14                NaN               93.0       15  237   60  ...   NaN  NaN
 15                NaN                3.8        0  NaN  NaN  ...   NaN  NaN
 16                NaN                2.0        0    7    1  ...  26.9    0
 17                NaN                NaN      NaN  NaN  NaN  ...   NaN  NaN
 18                NaN              179.6       33  547  159  ...  25.7   56
 19                NaN                3.8        0  NaN  NaN  ...   NaN  NaN
 20                NaN                2.0        0    7    1  ...  26.9    0

                Expected                               Unnamed: 24_level_0
      PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG             Matches
 0     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 1     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 2     0      1      NaN   NaN      NaN   NaN      NaN             Matches
 3     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 4     1      1      NaN   NaN      NaN   NaN      NaN             Matches
 5     2      3      5.5   3.1     0.06  -1.5     -1.1             Matches
 6     0      0      2.1   2.1     0.05  -1.1     -1.1             Matches
 7     1      1      5.7   4.9     0.07  -1.7     -1.9             Matches
 8     4      5     10.2   6.3     0.06  -3.2     -3.3             Matches
 9     0      0      0.3   0.3     0.04  -0.3     -0.3             Matches
 10    0      0      NaN   NaN      NaN   NaN      NaN             Matches
 11    8     11     23.7  16.6     0.06  -7.7     -7.6                 NaN
 12   PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG             Matches
 13    8     10     23.4  16.4     0.06  -7.4     -7.4                 NaN
 14    0      1      NaN   NaN      NaN   NaN      NaN                 NaN
 15    0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 16    0      0      0.3   0.3     0.04  -0.3     -0.3                 NaN
 17  NaN    NaN      NaN   NaN      NaN   NaN      NaN                 NaN
 18    8     11     23.4  16.4     0.06  -7.4     -7.4                 NaN
 19    0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 20    0      0      0.3   0.3     0.04  -0.3     -0.3                 NaN

 [21 rows x 25 columns],
             Unnamed: 0_level_0          Unnamed: 1_level_0  \
                         Season                         Age
 0                         2014                          20
 1                         2015                          21
 2                         2016                          22
 3                         2017                          23
 4                         2018                          24
 5                         2019                          25
 6                         2020                          26
 7                         2021                          27
 8                         2022                          28
 9                    2022-2023                          28
 10                   2023-2024                          29
 11                  10 Seasons                  10 Seasons
 12                         NaN                         NaN
 13       Palmeiras (5 Seasons)       Palmeiras (5 Seasons)
 14      Fluminense (4 Seasons)      Fluminense (4 Seasons)
 15       Olympiacos (1 Season)       Olympiacos (1 Season)
 16  Nott'ham Forest (1 Season)  Nott'ham Forest (1 Season)
 17                         NaN                         NaN
 18         Série A (9 Seasons)         Série A (9 Seasons)
 19     Super League (1 Season)     Super League (1 Season)
 20   Premier League (1 Season)   Premier League (1 Season)

             Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                          Squad            Country               Comp
 0                   Fluminense             br BRA         1. Série A
 1                   Fluminense             br BRA         1. Série A
 2                   Fluminense             br BRA         1. Série A
 3                   Fluminense             br BRA         1. Série A
 4                    Palmeiras             br BRA         1. Série A
 5                    Palmeiras             br BRA         1. Série A
 6                    Palmeiras             br BRA         1. Série A
 7                    Palmeiras             br BRA         1. Série A
 8                    Palmeiras             br BRA         1. Série A
 9              Nott'ham Forest            eng ENG  1. Premier League
 10                  Olympiacos             gr GRE    1. Super League
 11                     4 Clubs                NaN          3 Leagues
 12                         NaN            Country               Comp
 13       Palmeiras (5 Seasons)                NaN           1 League
 14      Fluminense (4 Seasons)                NaN           1 League
 15       Olympiacos (1 Season)                NaN           1 League
 16  Nott'ham Forest (1 Season)                NaN           1 League
 17                         NaN                NaN                NaN
 18         Série A (9 Seasons)                NaN                NaN
 19     Super League (1 Season)                NaN                NaN
 20   Premier League (1 Season)                NaN                NaN

    Unnamed: 5_level_0 Unnamed: 6_level_0 Total              ...  \
                LgRank                90s   Cmp   Att  Cmp%  ...
 0                 6th                0.4   NaN   NaN   NaN  ...
 1                13th               24.2   NaN   NaN   NaN  ...
 2                13th               33.3   NaN   NaN   NaN  ...
 3                14th               35.1   NaN   NaN   NaN  ...
 4                 1st                7.3   NaN   NaN   NaN  ...
 5                 3rd               17.4   569   782  72.8  ...
 6                 7th               13.0   503   708  71.0  ...
 7                 3rd               20.4   688   991  69.4  ...
 8                 1st               28.6   971  1441  67.4  ...
 9                16th                2.0    51    78  65.4  ...
 10                3rd                3.8   NaN   NaN   NaN  ...
 11                NaN              185.4  2782  4000  69.6  ...
 12             LgRank                90s   Cmp   Att  Cmp%  ...
 13                NaN               86.6  2731  3922  69.6  ...
 14                NaN               93.0   NaN   NaN   NaN  ...
 15                NaN                3.8   NaN   NaN   NaN  ...
 16                NaN                2.0    51    78  65.4  ...
 17                NaN                NaN   NaN   NaN   NaN  ...
 18                NaN              179.6  2731  3922  69.6  ...
 19                NaN                3.8   NaN   NaN   NaN  ...