In [14]:
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
import pandas as pd
from time import sleep
from termcolor import colored as corzinha

In [20]:
options = Options()
service = executable_path=FirefoxService(GeckoDriverManager().install())
url = 'https://www.transfermarkt.com.br/campeonato-brasileiro-serie-a/formtabelle/wettbewerb/BRA1?saison_id=2022&min=1&max=1'
options = webdriver.FirefoxOptions()
options.headless = True
driver = webdriver.Firefox(options=options, service=service)
driver.get(url)
driver.maximize_window()
#driver.implicitly_wait(10)
ac = ActionChains(driver)

In [21]:
#Trocar de frame para aceitar o termo
driver.switch_to.frame(1)
button = driver.find_element(By.XPATH, "//button[contains(.,'Aceitar e continuar')]")
button.click()
sleep(3)
driver.switch_to.default_content()

In [19]:
# Navegue até a página que contém a tabela
driver.get("https://www.transfermarkt.com.br/campeonato-brasileiro-serie-a/formtabelle/wettbewerb/BRA1?saison_id=2022&min=1&max=1")

# Use o XPath fornecido para localizar o corpo da tabela
table_body_xpath = "//*[@id='main']/main/div[2]/div[1]/div/div[2]/table/tbody"
table_body = driver.find_element(By.XPATH, table_body_xpath)

# Inicialize um DataFrame vazio
df = pd.DataFrame(columns=["Posicao", "Clube", "Rodada", "Vitorias", "Empates", "Derrotas", "Gols", "SG", "Pts"])

# Encontre todas as linhas da tabela no corpo da tabela
rows = table_body.find_elements(By.TAG_NAME, "tr")

for row in rows:
    # Encontre todas as células de dados (td) na linha
    dados = row.find_elements(By.TAG_NAME, "td")

    # Extrair os dados de cada célula e adicionar uma linha ao DataFrame
    df.loc[len(df)] = [dados[0].text, dados[2].text, dados[3].text, dados[4].text, dados[5].text, dados[6].text, dados[7].text, dados[8].text, dados[9].text]

# Imprima o DataFrame
print(df)

KeyboardInterrupt

In [22]:
p = 0 #página
# Número máximo de rodadas
max_rodadas = 38  # Substitua pelo número desejado

# Inicialize um DataFrame vazio
df = pd.DataFrame(columns=["Posicao", "Clube", "Rodada", "Vitorias", "Empates", "Derrotas", "Gols", "SG", "Pts"])

for rodada in range(1, max_rodadas + 1):
    # Construa a URL com o número da rodada
    url = f"https://www.transfermarkt.com.br/campeonato-brasileiro-serie-a/formtabelle/wettbewerb/BRA1?saison_id=2022&min=1&max={rodada}"
    p += 1
    print(f'entrando na rodada {p}')
    # Navegue até a URL
    driver.get(url)

    # Use o XPath fornecido para localizar o corpo da tabela
    table_body_xpath = "//*[@id='main']/main/div[2]/div[1]/div/div[2]/table/tbody"
    table_body = driver.find_element(By.XPATH, table_body_xpath)

    # Encontre todas as linhas da tabela no corpo da tabela
    rows = table_body.find_elements(By.TAG_NAME, "tr")

    for row in rows:
        # Encontre todas as células de dados (td) na linha
        dados = row.find_elements(By.TAG_NAME, "td")

        # Extrair os dados de cada célula e adicionar uma linha ao DataFrame
        df.loc[len(df)] = [dados[0].text, dados[2].text, dados[3].text, dados[4].text, dados[5].text, dados[6].text, dados[7].text, dados[8].text, dados[9].text]

# Feche o navegador quando terminar
driver.quit()

entrando na rodada 1
entrando na rodada 2
entrando na rodada 3
entrando na rodada 4
entrando na rodada 5
entrando na rodada 6
entrando na rodada 7
entrando na rodada 8
entrando na rodada 9
entrando na rodada 10
entrando na rodada 11
entrando na rodada 12
entrando na rodada 13
entrando na rodada 14
entrando na rodada 15
entrando na rodada 16
entrando na rodada 17
entrando na rodada 18
entrando na rodada 19
entrando na rodada 20
entrando na rodada 21
entrando na rodada 22
entrando na rodada 23
entrando na rodada 24
entrando na rodada 25
entrando na rodada 26
entrando na rodada 27
entrando na rodada 28
entrando na rodada 29
entrando na rodada 30
entrando na rodada 31
entrando na rodada 32
entrando na rodada 33
entrando na rodada 34
entrando na rodada 35
entrando na rodada 36
entrando na rodada 37
entrando na rodada 38

In [23]:
#Inspecionando
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 760 entries, 0 to 759
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Posicao   760 non-null    object
 1   Clube     760 non-null    object
 2   Rodada    760 non-null    object
 3   Vitorias  760 non-null    object
 4   Empates   760 non-null    object
 5   Derrotas  760 non-null    object
 6   Gols      760 non-null    object
 7   SG        760 non-null    object
 8   Pts       760 non-null    object
dtypes: object(9)
memory usage: 59.4+ KB

In [29]:
#Renomeando alguns times
df['Clube'] = df['Clube'].str.replace('Athletico-PR', 'Athletico_PR')
df['Clube'] = df['Clube'].str.replace('Atlético-MG', 'Atlético_MG')
df['Clube'] = df['Clube'].str.replace('América-MG', 'América_MG')
df['Clube'] = df['Clube'].str.replace('Vasco da Gama  ', 'Vasco da Gama')
df['Clube'] = df['Clube'].str.replace('Grêmio  ', 'Grêmio')
df['Clube'] = df['Clube'].str.replace('Bahia  ', 'Bahia')
df['Clube'] = df['Clube'].str.replace('Cruzeiro  ', 'Cruzeiro')

In [30]:
#Verificando os times
df['Clube'].unique()

array(['Flamengo', 'Fluminense', 'Athletico_PR', 'Botafogo',
       'Corinthians', 'Palmeiras', 'Bragantino', 'Vasco da Gama',
       'Grêmio', 'Fortaleza', 'Internacional', 'Atlético_MG', 'Bahia',
       'Cruzeiro', 'Cuiabá', 'São Paulo', 'Santos', 'Goiás', 'América_MG',
       'Coritiba'], dtype=object)

In [31]:
#Puxando a rodada
df[df['Rodada'] == "38"]

    Posicao          Clube Rodada Vitorias Empates Derrotas   Gols   SG Pts
740      1       Palmeiras     38       20      10        8  64:33   31  70
741      2          Grêmio     38       21       5       12  63:56    7  68
742      3     Atlético_MG     38       19       9       10  52:32   20  66
743      4        Flamengo     38       19       9       10  56:42   14  66
744      5        Botafogo     38       18      10       10  58:37   21  64
745      6      Bragantino     38       17      11       10  49:35   14  62
746      7    Athletico_PR     38       14      14       10  51:43    8  56
747      8      Fluminense     38       16       8       14  51:47    4  56
748      9   Internacional     38       15      10       13  46:45    1  55
749     10       Fortaleza     38       15       9       14  45:44    1  54
750     11       São Paulo     38       14      11       13  40:38    2  53
751     12          Cuiabá     38       14       9       15  40:39    1  51
752     13     Corinthians     38       12      14       12  47:48   -1  50
753     14        Cruzeiro     38       11      14       13  35:32    3  47
754     15   Vasco da Gama     38       12       9       17  41:51  -10  45
755     16           Bahia     38       12       8       18  50:53   -3  44
756     17          Santos     38       11      10       17  39:64  -25  43
757     18           Goiás     38        9      11       18  36:53  -17  38
758     19        Coritiba     38        8       6       24  41:73  -32  30
759     20      América_MG     38        5       9       24  42:81  -39  24

In [32]:
#Exportando para Json
df.to_json(f'D:/pythonProject/Tutoriais/data/processed/transfermkt_{max_rodadas}r_br23.json')